Revert "pktgen: Allow configuration of IPv6 source address range"
This reverts commit 7be3b20e71e0f5236bb747b33fa0f993c872e8b2.

It causes build failures on 32-bit, for example:

   net/core/pktgen.o: In function `mod_cur_headers':
>> pktgen.c:(.text.mod_cur_headers+0xba0): undefined reference to `__umoddi3'

Signed-off-by: David S. Miller <davem@davemloft.net>