ANDROID: Fix kenelci build-break for !CONFIG_PERF_EVENTS
Kernelci builds were broken if !CONFIG_PERF_EVENTS since 6ee53c54cad0 ("ANDROID: cpu/hotplug:
avoid breaking Android ABI by fusing cpuhp steps") causes
perf_event_init_cpu(cpu) to be reduced to "NULL(cpu)":

kernel/cpu.c:1868:21: error: called object type 'void *' is not a function or function pointer

Fixes: 6ee53c54cad0 ("ANDROID: cpu/hotplug: avoid breaking Android ABI by fusing cpuhp steps")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Ifc7351f74470c87018770395af4b4f6096f0d73f